In [89]:
#Implementing Logistic-Regression Algorithm 
#This algorithm is used for classfication of objects.
#Data-Set used in this program is Iris data-set.
#Link for dataset = http://scikit-learn.org/stable/auto_examples/datasets/plot_iris_dataset.html

#get the iris dataset.
from sklearn import datasets
import numpy as np
iris = datasets.load_iris()

#get features from the iris dataset.
features = iris.data

#get labels.
labels = np.array(iris.target).reshape(-1,1)


print('Iris Dataset')
print('Features Shape {0}'.format(features.shape))
print('Labels Shape {0}'.format(labels.shape))

print('\nSample Example')
print('Example 1 : {0} , Label = {1}'.format(features[0,:],labels[0]))

Iris Dataset
Features Shape (150, 4)
Labels Shape (150, 1)

Sample Example
Example 1 : [ 5.1  3.5  1.4  0.2] , Label = [0]


In [90]:
#Performing Feature Scaling and Mean Normalization
#This helps to make the algorithm converge faster == faster results.
#mean normalization = (feature[:,i] - mean_i_col) , for all i.
#feature scaling = (feature[:,i] - mean_i_col)/std_i_col , for all i.
#std_i_col = standard deviation of the ith column.

print("Sample Examples Before : ")
print(features[:4,:])

shape = features.shape
for i in range(shape[1]):
    mean = features[:,i].mean()
    std = np.std(features[:,i]) #standard deviation
    features[:,i] = (features[:,i]-mean)/std
    
print("\nSample Examples After : ")
print(features[:4,:])
print('\nRange of values of features approx = (-3,3)')


Sample Examples Before : 
[[ 5.1  3.5  1.4  0.2]
 [ 4.9  3.   1.4  0.2]
 [ 4.7  3.2  1.3  0.2]
 [ 4.6  3.1  1.5  0.2]]

Sample Examples After : 
[[-0.90068117  1.03205722 -1.3412724  -1.31297673]
 [-1.14301691 -0.1249576  -1.3412724  -1.31297673]
 [-1.38535265  0.33784833 -1.39813811 -1.31297673]
 [-1.50652052  0.10644536 -1.2844067  -1.31297673]]

Range of values of features approx = (-3,3)


In [91]:
#breaking the dataset into train_dataset, valid_dataset, test_dataset

#train_dataset
train_dataset = features[:120,:]
train_labels = labels[:120,:]

#cross_validation dataset
valid_dataset = features[120:135,:]
valid_labels = labels[120:135,:]

#test_dataset
test_dataset = features[135:150,:]
test_labels = labels[135:150,:]

print('train_dataset = {0} , train_labels = {1}'.format(train_dataset.shape, train_labels.shape))
print('valid_dataset = {0} , valid_labels = {1}'.format(valid_dataset.shape, valid_labels.shape))
print('test_dataset = {0} , test_labels = {1}'.format(test_dataset.shape, test_labels.shape))

train_dataset = (120, 4) , train_labels = (120, 1)
valid_dataset = (15, 4) , valid_labels = (15, 1)
test_dataset = (15, 4) , test_labels = (15, 1)


In [100]:
#Implementing Logistic-Regression.
#Link for LogisticRegression = http://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegression.html

#get linear_model library 
from sklearn import linear_model

#get logistic_Regression and assign values to the parameters
#to know about parameters check above link.
log_reg = linear_model.LogisticRegression(C=100,multi_class='ovr',solver='liblinear',max_iter=100)

#fit the training dataset.
log_reg.fit(train_dataset,train_labels)

#for predictions
train_prediction = log_reg.predict(train_dataset)

#check accuracy
print('Training Accuracy   : {0} %'.format(log_reg.score(train_dataset,train_labels)*100))
print('Validation Accuracy : {0} %'.format(log_reg.score(valid_dataset,valid_labels)*100))
print('Test Accuracy       : {0} %'.format(log_reg.score(test_dataset,test_labels)*100))

Training Accuracy   : 99.16666666666667 %
Validation Accuracy : 80.0 %
Test Accuracy       : 93.33333333333333 %


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:547: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
